# My variables
name: Rodney Norris
title: Rodney Norris
description: Tattooed Code Monkey
google_verification: null
baseurl: ""
permalink: /blog/:year/:i_month/:i_day/:title

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "vendor/", "Procfile", "Gemfile", "Gemfile.lock"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
highlighter: rouge

# Google services
google_analytics: UA-85970601-1
